development:
  adapter: postgresql
  encoding: unicode
  database: test2
  pool: 5
  username: postgres
  password: root


test:
  adapter: postgresql
  encoding: unicode
  database: test2
  pool: 5
  username: postgres
  password: root